import styled from "styled-components";
import tw from "tailwind.macro";

const Grid = styled.div.attrs({
    className: ""
  })`
    & {
      .w-full {
        ${tw`w-full`}
      }
      .w-1/2 {
        ${tw`w-1/2`}
      }
      .w-1/3 {
        ${tw`w-1/3`}
      }
      .w-2/3 {
        ${tw`w-2/3`}
      }
      .w-1/4 {
        ${tw`w-1/4`}
      }
      .w-2/4{
        ${tw`w-2/4`}
      }
      .w-3/4{
        ${tw`w-3/4`}
      }
      .w-1/5 {
        ${tw`w-1/5`}
      }
      .w-2/5 {
        ${tw`w-2/5`}
      }
      .w-3/5 {
        ${tw`w-3/5`}
      }
      .w-4/5 {
        ${tw`w-4/5`}
      }
      .w-1/6 {
        ${tw`w-1/6`}
      }
      .w-2/6 {
        ${tw`w-2/6`}
      }
      .w-3/6 {
        ${tw`w-3/6`}
      }
      .w-4/6 {
        ${tw`w-4/6`}
      }
      .w-5/6 {
        ${tw`w-5/6`}
      }
      .-mx-1{
        ${tw`-mx-1`}
      }
      .-mx-2{
        ${tw`-mx-2`}
      }
      .-mx-3{
        ${tw`-mx-3`}
      }
      .-mx-4{
        ${tw`-mx-4`}
      }
      .-mx-5{
        ${tw`-mx-5`}
      }
      .-mx-6{
        ${tw`-mx-6`}
      }
      .-mx-7{
        ${tw`-mx-7`}
      }
      .-mx-8{
        ${tw`-mx-8`}
      }
      .-mx-9{
        ${tw`-mx-9`}
      }
      .-mx-10{
        ${tw`-mx-10`}
      }
      .-mx-11{
        ${tw`-mx-11`}
      }
      .-mx-12{
        ${tw`-mx-12`}
      }
      .px-1{
        ${tw`px-1`}
      }
      .px-2{
        ${tw`px-2`}
      }
      .px-3{
        ${tw`px-3`}
      }
      .px-4{
        ${tw`px-4`}
      }
      .px-5{
        ${tw`px-5`}
      }
      .px-6{
        ${tw`px-6`}
      }
      .px-7{
        ${tw`px-7`}
      }
      .px-8{
        ${tw`px-8`}
      }
      .px-9{
        ${tw`px-9`}
      }
      .px-10{
        ${tw`px-10`}
      }
      .px-11{
        ${tw`px-11`}
      }
      .px-12{
        ${tw`px-12`}
      }
      .row {
        ${tw`flex mb-4`}
      }
      .flex {
        ${tw`flex`}
      }
      .flex-1{
        ${tw`flex-1`}
      }
      .flex-wrap{
        ${tw`flex-wrap`}
      }
      .mb-1{
        ${tw`mb-1`}
      }
      .mb-2{
        ${tw`mb-2`}
      }
      .mb-3{
        ${tw`mb-3`}
      }
      .mb-4{
        ${tw`mb-4`}
      }
      .mb-5{
        ${tw`mb-5`}
      }
      .mb-6{
        ${tw`mb-6`}
      }
      .mb-7{
        ${tw`mb-7`}
      }
      .mb-8{
        ${tw`mb-8`}
      }
      .h-1{
        ${tw`h-1`} 
      }
      .h-2{
        ${tw`h-2`} 
      }
      .h-3{
        ${tw`h-3`} 
      }
      .h-4{
        ${tw`h-4`} 
      }
      .h-5{
        ${tw`h-5`} 
      }
      .h-6{
        ${tw`h-6`} 
      }
      .h-7{
        ${tw`h-7`} 
      }
      .h-8{
        ${tw`h-8`} 
      }
      .h-9{
        ${tw`h-9`} 
      }
      .h-10{
        ${tw`h-10`} 
      }
      .h-11{
        ${tw`h-11`} 
      }
      .h-12{
        ${tw`h-12`} 
      }
      .ml-auto{
        ${tw`ml-auto`}
      }
      .mr-auto{
        ${tw`mr-auto`}
      }
      .grid{
        ${tw`grid`}
      }
      .gap-1{
        ${tw`gap-1`}
      }
      .gap-2{
        ${tw`gap-2`}
      }
      .gap-3{
        ${tw`gap-3`}
      }
      .gap-4{
        ${tw`gap-4`}
      }
      .gap-5{
        ${tw`gap-5`}
      }
      .gap-6{
        ${tw`gap-6`}
      }
      .gap-7{
        ${tw`gap-7`}
      }
      .gap-8{
        ${tw`gap-8`}
      }
      .gap-9{
        ${tw`gap-9`}
      }
      .gap-10{
        ${tw`gap-10`}
      }
      .gap-11{
        ${tw`gap-11`}
      }
      .gap-12{
        ${tw`gap-12`}
      }
      .col-gap-1{
        ${tw`col-gap-1`}
      }
      .col-gap-2{
        ${tw`col-gap-2`}
      }
      .col-gap-3{
        ${tw`col-gap-3`}
      }
      .col-gap-4{
        ${tw`col-gap-4`}
      }
      .col-gap-5{
        ${tw`col-gap-5`}
      }
      .col-gap-6{
        ${tw`col-gap-6`}
      }
      .col-gap-7{
        ${tw`col-gap-7`}
      }
      .col-gap-8{
        ${tw`col-gap-8`}
      }
      .col-gap-9{
        ${tw`col-gap-9`}
      }
      .col-gap-10{
        ${tw`col-gap-10`}
      }
      .col-gap-11{
        ${tw`col-gap-11`}
      }
      .col-gap-12{
        ${tw`col-gap-12`}
      }
      .grid-cols-1{
        ${tw`grid-cols-1`}
      }
      .grid-cols-2{
        ${tw`grid-cols-2`}
      }
      .grid-cols-3{
        ${tw`grid-cols-3`}
      }
      .grid-cols-4{
        ${tw`grid-cols-4`}
      }
      .grid-cols-5{
        ${tw`grid-cols-5`}
      }
      .grid-cols-6{
        ${tw`grid-cols-6`}
      }
    }
    
  `;

export default Grid;